### ISSUE TITLE
Run loop scheduler

### ISSUE THREAD

**Issue by wuyuanyi135** [victimsnino/ReactivePlusPlus#131]
Hi, thanks for creating this great project that keep the reactive programming up!

I wonder whether there is an implementation or plan to implement the runloop scheduler as in the rxcpp library? I found it effective to implement the cooperative multiprocessing an embedded platform.  

Thanks!

**Comment by victimsnino** [comment]
Hi! Thanks for submitting feature request! :-)
Yeah, I have plan to implement this scheduler in the near future, most probably during this week

**Comment by wuyuanyi135** [comment]
Appreciate for that!

**Comment by victimsnino** [comment]
@wuyuanyi135 , i've merge run_loop. Can you check if it satisfies your requirements?

**Comment by wuyuanyi135** [comment]
Hi, @victimsnino . Many thanks for implementing this feature! I will check it out these days and get you back if I have some questions.
