### ISSUE TITLE
Polish early_unsubscribe

### ISSUE THREAD

**Issue by victimsnino** [victimsnino/ReactivePlusPlus#268]
early_unsubscribe feature works awesome, but we can also extend it via adding checks to callbacks if someone requested unsubscribe or not

**Comment by tcw165** [comment]
> adding checks to callbacks if someone requested unsubscribe or not

What "callbacks" are they?

**Comment by victimsnino** [comment]
I mean, something similar to your `take_until` like:
```cpp
  if (!state->is_stopped)
      sub.on_next(...);
```
but check for subscription state
