### ISSUE TITLE
Rpp doesn't compile - VS22 - Windows - Latest release

### ISSUE THREAD

**Issue by dilson-pieve** [victimsnino/ReactivePlusPlus#283]
Hi, I really need help. I've been trying to fix it for a long time.

I've been trying to compile _ReactivePlusPlus_, but for some reason it doesn't work.
Could you please help me to find a solution? 

I did as described [BUILDING.md](https://github.com/victimsnino/ReactivePlusPlus/blob/main/BUILDING.md) and it didn't work.
I'll show below the erros I found and what I did to create my project.

These are the **errors** messages when I try to build on Visual Studio 2022 version 4.8.04161:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3539	a template-argument cannot be a type that contains 'auto'	DemoRPP	D:\cpp\DemoRPP\DemoRPP\rpp\observers\specific_observer.hpp	81	
Error	C3539	a template-argument cannot be a type that contains 'auto'	DemoRPP	D:\cpp\DemoRPP\DemoRPP\rpp\observers\specific_observer.hpp	87	
Error	C3539	a template-argument cannot be a type that contains 'auto'	DemoRPP	D:\cpp\DemoRPP\DemoRPP\rpp\observers\specific_observer.hpp	94	
Error	C3539	a template-argument cannot be a type that contains 'auto'	DemoRPP	D:\cpp\DemoRPP\DemoRPP\rpp\observers\specific_observer.hpp	101	
Error	C2672	'rpp::details::member_overload<Type,SpecificObservable,rpp::details::subscribe_tag>::subscribe_impl': no matching overloaded function found	DemoRPP	D:\cpp\DemoRPP\DemoRPP\rpp\operators\fwd\subscribe.hpp	60	
Error	C2672	'make_specific_subscriber': no matching overloaded function found	DemoRPP	D:\cpp\DemoRPP\DemoRPP\rpp\operators\fwd\subscribe.hpp	60	
```

**This is how I created my project**:

(1) Empty C++ project on VS22 > Created main.cpp file ( https://pastebin.com/raw/qMBkwkiM )
main.cpp screenshot: [https://ibb.co/fpPbKP6](https://ibb.co/fpPbKP6)

(2) After that, I changed it to C++20 and later to C++ latest
C++20 project screenshot: [https://ibb.co/q9FRGGV](https://ibb.co/q9FRGGV)

(3) I downloaded  the latest release and I added it to my project. [rpp_release](https://github.com/victimsnino/ReactivePlusPlus/releases/tag/v0.1.2)
Added RPP screenshot: [https://ibb.co/3mPkdBk](https://ibb.co/3mPkdBk)

How I added to my project: `Properties > C/C++ > Additional Include Directories.`

* I can see that VS recognizes the folders and the lib - I can navigate inside the functions/methods definitions.
* I tried different paths when I added it to my project.
* I tried build x64 - Release and Debug mode

What should I do to fix it? 

Thanks in advance 

**EDIT: VS22 preview is the issue here**

**Comment by victimsnino** [comment]
Hi, 
I will check it now and return with some tip, but screenshot links are broken

**Comment by victimsnino** [comment]
UPD: Your source code is valid and compilable on my machine. What is your version of Visual Studio? I mean, version of IDE. Like `17.3.6` and etc? I think, you've placed compiler version?

**Comment by victimsnino** [comment]
UPD: Did same as you described:
1) Created empty project
2) Added source file with your code snippet
3) Changed C++ to C++20
4) Added include directory

Everything works as expected

**Comment by victimsnino** [comment]
UPD: Looks like it is issue of old versions of VS. @dilson-pieve, can you upgrade your VS and try again?

**Comment by victimsnino** [comment]
Still can't see your screenshots... You can attach it as is to you message

Yeah, looks like your VS is fresh.. What about compiler? Which MSVC are you using inside your VS? You can check it in Visual Studio Installer. Should be MSVC v143. Same about compiler for your project (one line above where you choose C++20 version)

**Comment by dilson-pieve** [comment]
I really don't know why you can see; what about this different host?
https://postimg.cc/gXMddGZW
https://postimg.cc/q6zrvWsC
https://postimg.cc/rzPcPFTG

Yes, it's v143. The screenshot shows it too, hope it'll be possible for you to see it

**Comment by victimsnino** [comment]
Yeah, i can see it for now

**Comment by victimsnino** [comment]
Reproduced with same version of VS 17.4.0 Preview 5.0. Looks like it is issue of "Preview" version. Stable version 17.3.6 works as expected. Could you try 17.3.6 (not Preview) instead?

**Comment by dilson-pieve** [comment]
I tried it with VS22 17.3.6 and it works as expected. You're right, the problem is VS22 preview.
I'm happy we found a solution. I'll use this version for now.

Thank you again!
