### ISSUE TITLE
timeout operator

### ISSUE THREAD

**Issue by wuyuanyi135** [victimsnino/ReactivePlusPlus#286]
The [timeout](https://reactivex.io/documentation/operators/timeout.html) operator can be very useful to implement when deal with the communication protocols. However, not all languages implemented this operator. Is there any plan to implement it in this library or is there some alternative with the existing operators?

Thanks!

**Comment by victimsnino** [comment]
Hi @wuyuanyi135,

Yeah, I have `timeout` in the "todo" list. I will raise up priority for this operator due to feature request from you =)

**Comment by wuyuanyi135** [comment]
Thanks a lot for bringing up the priority of my request! 

Actually, I do see many of the operators and sources I may need are still on the roadmap and I would like to help as much as I can. But my metaprogramming skill is too primitive to fully understand or contribute to this project. Do you have some materials about how this project was designed and made magics happen?

**Comment by victimsnino** [comment]
> Thanks a lot for bringing up the priority of my request!
> 
> Actually, I do see many of the operators and sources I may need are still on the roadmap and I would like to help as much as I can.

You can create issues for each operator that you need. It is important for me because:
1) currently I'm implementing operators blindly and actually don't know if someone need this one or another one
2) It is important to know that someone uses RPP =)

Also you can provide really good help via providing user's experience about library. I mean, does it comfortable to use or not? What i can to change/improve to make experience better and etc. Also you can submit some non-trivial examples if you want/have =)

> Do you have some materials about how this project was designed and made magics happen?

Some tricky questions described on docs page. What actually do you want to know?

**Comment by wuyuanyi135** [comment]
So impressed to see the devoted devs working on this project! I will surely report my requests soon. I managed to assemble some missing features since the Rx operators have some overlapped applications. (e.g., timer = interval + take(1)), but some workarounds may be too cumbersome and then I will make a request here. 

In terms of dev docs, as most of my experience is about application dev and only little with library/meta-programming, it might be even too early for me to ask a proper question :no_mouth: . But maybe a templated or one comment-documented source/operator/test/scheduler... might be a start point to derive the others from it?

**Comment by victimsnino** [comment]
> So impressed to see the devoted devs working on this project! I will surely report my requests soon. I managed to assemble some missing features since the Rx operators have some overlapped applications. (e.g., timer = interval + take(1)), but some workarounds may be too cumbersome and then I will make a request here

Thanks! Looking forward to!

> But maybe a templated or one comment-documented source/operator/test/scheduler... might be a start point to derive the others from it?

Not sure if I get your point. Every operator has long doxygen documentation with description of everything, marbles and examples like [this](https://victimsnino.github.io/ReactivePlusPlus/docs/html/group__combining__operators.html). Or are you asking about "internal comments" about "internal" logic?

**Comment by wuyuanyi135** [comment]
Yes, I am talking about the internal logics. The usages of the component are very clear in the docs and the tests. 

What I meant is some material such as this [one](https://rxpy.readthedocs.io/en/latest/get_started.html#custom-operator) from RxPY telling how a custom operator can be implemented. But I am not sure if it is too tedious to detail in the internal codes.

IMO, the best of RX is that 99% of what I need to create an async application can be done by composing the chain rather than touching the library itself. I will make sure to report to report those bottlenecking features 👍

**Comment by victimsnino** [comment]
Oh, i see. I would create some doc about implementing custom operators. Thanks for idea =)
