### ISSUE TITLE
Add average operator (and other statistical)

### ISSUE THREAD

**Issue by mincequi** [victimsnino/ReactivePlusPlus#307]
Hi @victimsnino 
i am opening another thread, since it might exceed my original request(s) a bit...

How open are you about non-(rx)-standard filters?

The `average` operator is already part of the original rx definition (which i also have a usage for).
However, other filters come to my mind like `exponential moving average` or `median` filtering. Those are realised in _influxdb_:
https://docs.influxdata.com/flux/v0.x/stdlib/universe/exponentialmovingaverage/
https://docs.influxdata.com/flux/v0.x/stdlib/universe/median/

I don't know, whether there are implementations for other languages, but those filters would be pretty helpful for financial, statistical and signal processing applications (and for my application...).

Looking forward to your opinion on that.

**Comment by victimsnino** [comment]
Hi @mincequi,
of course i would implement `average` operator. Most probably to do it i would need to implement `reduce` operator. As a result, it would be possible for any user to create their own operators based on `reduce` operator with help of providing only one callable/lambda to show "how to calculate what i want". So, it would be possible to implement it by this way.

I'm not sure that I'm ready to implement all of this statistical functions by my own, but you can create PRs for each of them after I implement `reduce` and if no any issues in your PR i would be glad to merge it :-)

**Comment by mincequi** [comment]
That sounds good to me. Could be a good exercise for me to implement those operators :-)

**Comment by victimsnino** [comment]
@mincequi, implemented! =)
