### ISSUE TITLE
Two broken links

### ISSUE THREAD

**Issue by juxeii** [victimsnino/ReactivePlusPlus#385]
Hi,

first, many thanks for this amazing library, which makes reactive finally usable in c++.

Please fix two broken links:

- Under `Documentation` the [manual documentation](https://github.com/victimsnino/ReactivePlusPlus/blob/v2) just links back to the github page itself.
- Under `Useful links` the [User Guide](https://victimsnino.github.io/ReactivePlusPlus/v2/docs/html/md_docs_readme.html) results in a 404.

Thx.

**Comment by victimsnino** [comment]
Hi!
Yeah, thank you for catching this issues. Looks like i've forget about it during migration to v2 =)
Fixed
