### ISSUE TITLE
Feature request for "Single-Observable"

### ISSUE THREAD

**Issue by juxeii** [victimsnino/ReactivePlusPlus#386]
Hi,

I would love to see
https://reactivex.io/documentation/single.html
implemented.

Thx.

**Comment by victimsnino** [comment]
Hi!
Thanks for your feature request. To be honest, I'm not sure if I would be able to touch this in near future: even "core" operators and things are still not implemented =)

If you are interested in implementing it by your own, I can provide help/consulting and any other help that you need to implement it and create PRs =)

**Comment by juxeii** [comment]
Nevermind. We've waited years to have a good reactive lib, we can wait some more years for such enhancements :)
It is just here that it will not be forgotten.
