### ISSUE TITLE
Create another v1 release

### ISSUE THREAD

**Issue by mincequi** [victimsnino/ReactivePlusPlus#417]
Hi there,
great to watch your effort on v2!

However, I am still using v1 since I am using operators and other stuff which is not completed yet for v2.
For v1 I also need a recent version, which I obtain via CMake's fetchcontent and a commit hash. This has same drawbacks, since it takes a lot of time to check out. A better way would be to rely on a tag/release. So, are you planning to create another (or last) release for the v1 branch?
That would be great :)

Thanks already.

**Comment by victimsnino** [comment]
Hi!
Sure, done https://github.com/victimsnino/ReactivePlusPlus/releases/tag/v0.2.3
=)
Anyway, it was so close to 0.2.2 by commits =)

BTW, what are you missing for using v2? I'm really interested in your usage/feedback as continuous user of RPP =)

**Comment by mincequi** [comment]
Hey, that was fast! Thanks!

As of now, I am missing debounce and combine :)

**Comment by victimsnino** [comment]
Would make them in close future =)

**Comment by victimsnino** [comment]
> Hey, that was fast! Thanks!
> 
> As of now, I am missing debounce and combine :)

FYI, @mincequi debounce and combine_latest implemented in v2 =)

**Comment by mincequi** [comment]
This is great news!
And -of course- I come up with another request ;)

Since I plan to use very long durations for debounce (e.g. 5 minutes), can I somehow be informed about the progress of the internal timer?

**Comment by victimsnino** [comment]
> This is great news! And -of course- I come up with another request ;)

That's the point to ask you about it =) So, you are welcome =)

> Since I plan to use very long durations for debounce (e.g. 5 minutes), can I somehow be informed about the progress of the internal timer?

Do you mean in realtime via some sort of callbacks? Or just logging for debugging and etc? Please, add more details (maybe some examples of expected/requested behavior) due to currently i can't understand final use-case for it =)

**Comment by mincequi** [comment]
> Do you mean in realtime via some sort of callbacks? Or just logging for debugging and etc? Please, add more details (maybe some examples of expected/requested behavior) due to currently i can't understand final use-case for it =)

The first one. Basically, I want to realise a countdown when the debounce operator emits its value (not for logging, etc). However, I am still working on that, so my request might be a little bit too early.
I will add some pseudo code, as soon as I can figure out a nice API. But, I guess, I could also easily work around this....

**Comment by victimsnino** [comment]
> > Do you mean in realtime via some sort of callbacks? Or just logging for debugging and etc? Please, add more details (maybe some examples of expected/requested behavior) due to currently i can't understand final use-case for it =)
> 
> The first one. Basically, I want to realise a countdown when the debounce operator emits its value (not for logging, etc). However, I am still working on that, so my request might be a little bit too early. I will add some pseudo code, as soon as I can figure out a nice API. But, I guess, I could also easily work around this....

OK, I see. Feel free to open new issue when you would have more details and understanding :)
