### ISSUE TITLE
Resolve "nano sleeps"

### ISSUE THREAD

**Issue by victimsnino** [victimsnino/ReactivePlusPlus#424]
Currently we are doing `sleep_for` inside schedulers. BUT sleeping is pretty expensive operation, so, if we are doing `sleep_for(std::chrono::nanoseconds{1})` actually it is about 18-50k nanoseconds sleep. So, actually sleep with duration <= 18-50k ns is unreachable with std.

UPD: Looks like clang/gcc uses nanosleep and it doesn't work
UPD: Looks like best possible solution: change RPP's granularity to microseconds instead

**Comment by victimsnino** [comment]
@mincequi, interested in your opinion if you want to discuss: what do you think about it? Does scheduling of anything with period <= 18-50k ns is real-possible usecase?

**Comment by mincequi** [comment]
Hey @victimsnino,
well, I am not an expert on this, but giving my two cents anyway ;)
Which kind of "customers" do you want to reach?
For a scientific application (measuring light speed) it cannot be fast and accurate enough. However, I doubt that any desktop application needs an accuracy that is smaller than 1ms. And I personally have no use for that either, even for realtime applications.
Googling around, I found this article, which might be helpful:
https://blat-blatnik.github.io/computerBear/making-accurate-sleep-function/

**Comment by victimsnino** [comment]
Yeah, it makes sense. Thank you for your point! And for interesting article :)

**Comment by mincequi** [comment]
One update: since I am planing to replace Qt in my project with this lib: https://libuv.org, I thought, it might also be a good resource for you. FYI.

**Comment by victimsnino** [comment]
Looks like it is not a goal/issue for now
