### ISSUE TITLE
Throttle operator

### ISSUE THREAD

**Issue by mincequi** [victimsnino/ReactivePlusPlus#466]
Hi there,
great to watch your progress with v2 and I already saw, that you are about to integrate Qt again.
I would have another request for an operator: this time it is "throttle".

Once Qt and throttle is there, I will switch to RppV2 and serve as tester :)

Thanks again and best regards!

**Comment by victimsnino** [comment]
Hi @mincequi!
Thanks for your feature-request and expectation for v2 =)

Could you explain a bit your expectations about this operator? In my understanding currently implemented [debounce](https://victimsnino.github.io/ReactivePlusPlus/v2/docs/html/group__utility__operators.html#ga49e91c6114f62ac261303814c818face) operator is actually throttle? If not, can you provide some details/difference then? :)

**Comment by mincequi** [comment]
Hi @victimsnino,

Ok, let me explain the difference.
'debounce' emits only after a particular time span has passed without another source emission.
'throttle' emits immediately but then ignores subsequent source emissions for a particular time span, then repeats this process.

You can also check:
https://rxjs.dev/api/operators/debounce
https://rxjs.dev/api/operators/throttle

**Comment by victimsnino** [comment]
@mincequi, everything is ready =)
