### ISSUE TITLE
Publish subject fails compilation on GCC 13

### ISSUE THREAD

**Issue by AidanGG** [victimsnino/ReactivePlusPlus#475]
Minimal example https://godbolt.org/z/T9P8G1PYq

Using the publish subject is fine in GCC 11 and 12 (but not 10 or 13). I'm not sure why 13 is complaining about the incomplete type.

Clang works from 14 onward.

**Comment by victimsnino** [comment]
Thank you for report. Looks like found root-cause of this issue. Fix in linked PR. Godbolt would get it during 1 day after merge

UPD: Looks like it is related to this one https://stackoverflow.com/questions/76943253/has-gcc13-changed-handling-of-noexcept-function-pointers, but trivial solution doesn't work for older versions -_-
UPD: Found more elegant way, but msvc..

**Comment by victimsnino** [comment]
Fixed
