### ISSUE TITLE
Reemit from subscription

### ISSUE THREAD

**Issue by mincequi** [victimsnino/ReactivePlusPlus#499]
Hi there,
another question regarding some detail about your lib (still on v1, though).
Apparently, there is some issue when emitting something from within a subscription.

The following won't work:
```
publish_subject<int> subject1;
publish_subject<int> subject2;
subject1.subscribe([](int value) {
  subject2.get_subscriber().on_next(value+1); // This will block
});
```
However, this will do the trick:
```
publish_subject<int> subject1;
publish_subject<int> subject2;
subject1.subscribe(subject2.get_subscriber());
```

Due to a complex operation, I would prefer something with the first syntax. (Instead of using the map operator or similar).
Can you give me a hint here, please?

Thanks already! :)

**Comment by victimsnino** [comment]
Hi @mincequi!

Sounds strange.. I'm not expecting any difference in provided snippets..

Anyway, I can't reproduce your issue on godbolt

https://godbolt.org/z/8Tzj6YK47

Could you provide some minimal repro?

**Comment by mincequi** [comment]
Hi @victimsnino,

hm, I am experiencing this completely reproducible within my app, however I did not check my example.
I will try to work out something very soon.

**Comment by mincequi** [comment]
Hi @victimsnino,

I found out, that it was actually my fault. I emitted from within a subscription to an observable, that retriggers the observable. So, basically and endless loop. Anyway, thanks for your fast support :)
