### ISSUE TITLE
How to refer to observable type anyway?

### ISSUE THREAD

**Issue by RobinQu** [victimsnino/ReactivePlusPlus#533]
It's a common practice to return an `observable<T>` to for a method to represent  values of `T` in async fashion.   

```
class Person {
   observable<std::string> Talk();
} 
```
While `rpp` does provide an `observable` class, but it has too many class template arguments which I can find very few explainations in docs. Before reading your whole project code, would you please enlighten me about a simple way to define actual class type other than `auto`.

**Comment by victimsnino** [comment]
Hello @RobinQu.

Yeah, you are right, currently it is not clear from documentation. Made #534 to explicitly explain it in document. hope it is clear enough. Feel free to ask any other questions =)

Direct link to paragraph:
https://victimsnino.github.io/ReactivePlusPlus/v2/docs/html/md_docs_2readme.html#autotoc_md13

**Comment by RobinQu** [comment]
Thanks for you response. I will have a try with `dynamic_*` classes.
