### ISSUE TITLE
Please update RPP in conan center

### ISSUE THREAD

**Issue by RobinQu** [victimsnino/ReactivePlusPlus#548]
As my current project relies heavily on conan, and coincidentally I am using `distinct` op in v2.1.0 as git submodule, please conisder updading package in conan.

At the time being, latest version on conan is still [v2.0.0](https://conan.io/center/recipes/reactiveplusplus?version=2.0.0). And I've requested [update request](https://github.com/conan-io/conan-center-index/issues/23287) at conan center. 

Let me know if anything I can do to speed up the process.

**Comment by victimsnino** [comment]
Hi, @RobinQu , 
To be honest all previous conan/vcpkg updates were done by some other people, not me 😅
I would try to investigate how to do it

**Comment by victimsnino** [comment]
@RobinQu , updated

**Comment by RobinQu** [comment]
Awesome!
