### ISSUE TITLE
What is the best way to add support for Unreal Engine's TMulticastDelegate as an observable? 

### ISSUE THREAD

**Issue by jcoder58** [victimsnino/ReactivePlusPlus#564]
Unreal Engine has [TMulticastDelegate](https://dev.epicgames.com/documentation/en-us/unreal-engine/API/Runtime/Core/Delegates/TMulticastDelegate_void_ParamTyp-?application_version=5.3) and I want to implement a source/observable for it.  Ideally, I want an operator| that takes a TMulticastDelegate on the left side and an observer on the right. Something like:

    BeginPlay | rpp::operators::subscribe([](){UE_LOG("Begin Play Now"); });

where BeginPlay is a TMulticastDelegate.

**Comment by victimsnino** [comment]
Hi @jcoder58 ,
I've checked documentation for delegates in UE. I think, it should be possible to do it in this way:
```cpp
#include <rpp/subjects/publish_subject.hpp>

template<typename... ParamTypes, typename UserPolicy>  
auto to_observable(const TMulticastDelegate< void(ParamTypes...), UserPolicy >& delegate)
{
   const auto subj = rpp::subjects::serialized_subject<std::tuple<ParamTypes...>>{}; // <-- technically it could be publish_subject to avoid extra std::mutex in case of you are sure there is no any async broadcasts
   delegate.AddLambda([obs = subj.get_observer()](const ParamType&... vals) { obs.on_next(std::tuple{vals...});
});
return subj.get_observable();
}
```

As far as i get UE is not providing any "termination"-like signals to subscribe for on_completed? Like event about destruction and etc?

Technically it is possible to override operator| but in this case you have to support all possible operator| overloadings (operators/subscribes and etc. I think it is much more harder comparing to this one)


UPD:
Another way is:
```cpp
#include <rpp/sources/create.hpp>

template<typename... ParamTypes, typename UserPolicy>  
auto to_observable(const TMulticastDelegate< void(ParamTypes...), UserPolicy >& delegate)
{
   return rpp::source::create<std::tuple<ParamTypes...>>([delegate](auto&& observer)
   {
      auto dynamic = std::forward<decltype(observer)>(observer).as_dynamic();
      const auto handle = delegate.AddLambda([dynamic](const ParamTypes& values...)
      {
          dynamic.on_next(std::tuple{values...});
      }); 
      dynamic.set_upstream(rpp::make_callback_disposable([handle, delegate]
                                                         { 
                                                            handle.Reset(); 
                                                            delegate.Remove(handle); // <-- not sure about this one
                                                          }));
   });
}
```
This one without extra indirect subject + it would correctly unbound observer from delegate so i would recommend to use this one

**Comment by jcoder58** [comment]
I've refactored a bit to figure out some of the errors I got.  This error I can't figure out.  Also, I couldn't find `serialized_subject` in v2 (or v1).

```
#include "rpp/rpp.hpp"

template<typename... ParamTypes, typename UserPolicy>
auto to_observable(TMulticastDelegate< void(ParamTypes...), UserPolicy >& delegate)
{
    const auto subj = rpp::subjects::publish_subject<std::tuple<ParamTypes...>>{};
    auto obs = subj.get_observer();
    auto func =[obs](const ParamTypes&... vals) { obs.on_next(std::tuple{ vals... });  };
    // Error: 'rpp::observer<Type,rpp::subjects::details::publish_subject_base<Type,false>::observer_strategy>::observer(const rpp::observer<Type,rpp::subjects::details::publish_subject_base<Type,false>::observer_strategy> &)': attempting to reference a deleted function	

    delegate.AddLambda(func);
        
    return subj.get_observable();
}
```

AddLambda returns an FDelegateHandle which has a Reset() function that will remove a subscription.  However, the delegates I'm interested in have a lifetime of the app, so there will be no need for on_complete.  There is a signal that is sent when the app is terminated instead.

**Comment by victimsnino** [comment]
observer is not copyable by default so your exact code would not be compilable. You should add std::move(obs) and std::move(func) (in case of no any other copies inside `AddLambda` call) or you can update observer creation to `subj.get_observer().as_dynamic()` to make it dynamic and copyable (due to wrapping to std::shared_ptr). Anyway second approach from my original message looks more correct for me.

> Also, I couldn't find serialized_subject in v2 (or v1).

Yeah, my bad, it called `serialized_publish_subject`

**Comment by jcoder58** [comment]
Turns out AddLambda wants a copyable as well, so I went to your second code.  I fixed a few errors and came up with this:

```C++
#include "CoreMinimal.h"
#include "rpp/rpp.hpp"

template<typename... ParamTypes, typename UserPolicy>
auto to_observable(TMulticastDelegate< void(ParamTypes...), UserPolicy >& del)
{
    return rpp::source::create<std::tuple<ParamTypes...>>([&del](auto&& observer)
        {
            auto dynamic = std::forward<decltype(observer)>(observer).as_dynamic();
            auto handle = del.AddLambda([dynamic](const ParamTypes&... values)
                {
                    dynamic.on_next(std::forward_as_tuple(values...));
                });
            //dynamic.set_upstream(rpp::make_callback_disposable([handle, &del]
            //    {
            //         handle.Reset(); 
            //        del.Remove(handle); // <-- not sure about this one
            //    }));
        });
}
```

It compiles, except for the commented out code which fails because handle wants to be mutable.    I'll figure that out later.
