### ISSUE TITLE
Debounce hangs with libuv integration

### ISSUE THREAD

**Issue by mincequi** [victimsnino/ReactivePlusPlus#609]
Hi @victimsnino,
hopefully, i can bother you with another request, but i am having a problem with the debounce operator and libuv/uvw eventloop integration. And i also do not see an issue with my part, so maybe you can help (or point me to somewhere else, since it might be a bug with libuv or my integration code).

I wrote a unit test to reproduce this behaviour:
https://github.com/mincequi/uvw_iot/blob/main/tests/RppUvwTest.cpp

And this is my uvw integration for rpp:
https://github.com/mincequi/uvw_iot/blob/main/uvw_iot/RppUvw.h

Especially on low-powered machines, the debounce operator does not emit anymore (but rx stream does not complete).

Do you have any idea?
Thanks a lot!

**Comment by victimsnino** [comment]
Hi @mincequi !
Yeah, you are welcome =)

This code looks fine for me. It even works fine for me...
```cpp
~/uvw_iot/b/tests main ❯ /home/victimsnino/uvw_iot/build/tests/tests
Randomness seeded to: 1379457251
debounceCount: 1000
debounceCount: 2000
debounceCount: 3000
debounceCount: 4000
debounceCount: 5000
```

So, looks like classical answer "it works on my station" :-)
Anyway, my first thought about it: i would suggest you to log [this](https://github.com/mincequi/uvw_iot/blob/main/uvw_iot/RppUvw.h#L18) place to be sure if your callback was called at all (for example, does uvw guarantees strict order evaluation of timers?).

**Comment by victimsnino** [comment]
UPD:
reproduced it via adding some "useful workload" at the begin of test:
```cpp
    for (size_t i =0; i < 100; ++i) {
        rpp::source::just(1)
        | rpp::ops::repeat()
        | rpp::ops::subscribe_on(rpp::schedulers::new_thread{})
        | rpp::ops::subscribe();
    }
```

So, yes, in this case timer from main_thread_scheduler is never firing for some reason ¯\_(ツ)_/¯

**Comment by victimsnino** [comment]
Spot it!
https://github.com/mincequi/uvw_iot/blob/main/uvw_iot/RppUvw.h#L49 <- there `new_tp->value` can be less than `rpp::schedulers::clock_type::now()`. In this case you are going to schedule it "to the past". My schedulers works fine with that (due to absolute comparison of timestamps and obtaining just "minimal"). But uvw handles it in this way 
```cpp
clamped_timeout = handle->loop->time + timeout;
  if (clamped_timeout < timeout)
    clamped_timeout = (uint64_t) -1;
```
Utimeout is uint64_t based value, )while duration in rpp is int64_t, so, it just does overflow and etc... so, negative duration goes to the end of queue

**Comment by mincequi** [comment]
Awesome, thanks a lot...i should have known that... 😬
