### ISSUE TITLE
Using reactiveplusplus with vcpkg and MSBuild

### ISSUE THREAD

**Issue by idotta** [victimsnino/ReactivePlusPlus#610]
Hey there! Firstly, thanks for this wonderful library!

Has anyone tried using reactiveplusplus with **vcpkg** and **MSBuild**? I'm currently using it as a submodule and it works great, but I'd like to start using vcpkg (already using it for other dependencies). 

It seems the installation folder is a level before, so I can access it by including `rpp/rpp/rpp.hpp` but that doesn't solve the issue, since the other files depend on the correct location. Any clues?

**Comment by victimsnino** [comment]
Hey @idotta!
Looks pretty interesting.. unfortunately i can't access windows-based machine for some time so i can't check/reproduce it.
As far as i know [this pr](https://github.com/andreamancuso/react-wasm/pull/31/files) is successful usage of rpp via vcpkg but not sure about MSBuild... Anyway, i think it could help if you would make some short simple example to reproduce issue =)

**Comment by idotta** [comment]
Hey @victimsnino! Yeah, it works with CMake. However it doesn't work correctly with MSBuild. I created an [issue](https://github.com/microsoft/vcpkg/issues/39940) in the vcpkg repository and they suggested to work around it by adding a new include directory to the solution.

This is the [working sample](https://github.com/idotta/rpp-msbuild) that I created for future reference. Thanks!
