### ISSUE TITLE
Connect example output different than expected

### ISSUE THREAD

**Issue by wjspoel** [victimsnino/ReactivePlusPlus#645]
Hi, 

Thanks for the great repo!

I tried out your [connect ](https://github.com/victimsnino/ReactivePlusPlus/blob/v2/src/examples/rpp/doxygen/connect.cpp)example as is on [godbolt](https://godbolt.org/z/a6qcsP7KG) but the output seems different. It never reaches printing the CONNECT message. Is that expected?

Regards,
Willem

**Comment by victimsnino** [comment]
Hi @wjspoel!
For me it is starting from CONNECT message and then showing value in map till timeout of godbolt session reached.
Maybe you meant SUBSCRIBE or DISPOSE message due to it is actually blocks inside connect call... have to debug a bit, it is unexpected behavior

**Comment by victimsnino** [comment]
UPD: found root cause, fixed, thanks for catching =)
